Django_cbv/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from .custom_site import custom_site
from django.contrib.sitemaps import views as sitemap_views
from django.views.decorators.cache import cache_page
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap

from blog.views import IndexView, CategoryView, TagView, PostDetailView, SearchView, AuthorView
from config.views import LinkListView
from comment.views import CommentView
from blog.apis import post_list, PostList
from blog.api import PostViewSet, CategoryViewSet
from rest_framework.documentation import include_docs_urls  # 用于配置接口文档
from rest_framework.routers import DefaultRouter  # Django rest framework 的路由配置


router = DefaultRouter()
router.register(r'post', PostViewSet, base_name='api-post')
router.register(r'category', CategoryViewSet, base_name='api-category')



urlpatterns = [
    # 路由配置及参数传递均没有问题
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    url(r'^search/$', SearchView.as_view(), name='search'),  # 用于搜索功能
    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author'),
    # 分组命名匹配、这个url有问题！！！对于FBV没有问题
    url(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name='post-detail'),
    url(r'^links/$', LinkListView.as_view(), name='links'),
    url(r'^rss|feed/', LatestPostFeed(), name='rss'),
    url(r'^sitemap\.xml$', cache_page(60 * 20, key_prefix='sitemap_cache_')(sitemap_views.sitemap),{'sitemaps': {'posts': PostSitemap}}),
    url(r'^apis/post', post_list, name='post-list'),  # 该url目前无法访问
    url(r'^api/docs/', include_docs_urls(title='Bruce apis')),  # 配置接口文档
    # url(r'^api/', include(router.urls, namespace='api')),  # 配置接口文档

    # 后台管理url
    url(r'^super_admin/', admin.site.urls, name='super-admin'),  # 超级用户
    url(r'^admin/', custom_site.urls, name='admin'),  # 普通用户

]

comment/models.py
from django.db import models

class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    target = models.CharField(max_length=100, verbose_name="评论目标")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = verbose_name_plural = "评论"

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

comment/forms.py
# -*- coding: utf-8 -*-
"""
@name:        
@function：   
@step:        
@author: Bruce
@contact: zhu.chaoqiang@byd.com
@Created on: 2019/10/25 10:41

"""
import mistune
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )

    content = forms.CharField(
        label="内容",
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'rows': 6, 'cols': 60, 'class': 'form-control'}
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('内容长度怎么能这么短呢！！')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

comment/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView
from .forms import CommentForm


class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

Django_cbv/themes/bootstrap/templates/comment/block.html
<hr/>
<div class="comment">
    <form id="comment_form" class="form-group" action="/comment/" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}"/>
        {{ comment_form }}
        <div id="captcha_section"></div>
        <input id="verify" type="button" value="写好了!"/>
        <input id="submit" type="submit" style="display:None" value="写好了!"/>
    </form>

    <!-- 评论列表 -->
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a> <span>{{ comment.created_time }}</span>
            </div>
            <div class="comment-content">
                {% autoescape off %}
                {{ comment.content }}
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        var $form = $('.form-group');
        function init_captcha() {
            $.getJSON("{% url 'verify_captcha' %}", function(data) {
                $('#captcha_section').html(
                    '<img src="' + data.image_src +'" id="captcha_id" data-id="'+ data.captcha_id +'"/>' + 
                    '<input id="captcha"/>'
                );
            })
        }
        $( document ).on( "click", '#captcha_id', init_captcha);

        $('#verify').on('click', function() {
            var captcha = $('#captcha').val();
            if (!captcha) {
                alert('验证码不能为空');
                return;
            }
            $.ajax({
                url: "{% url 'verify_captcha' %}",
                method: 'POST',
                data: {
                    'captcha_id': $('#captcha_id').data('id'),
                    'captcha': captcha,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function() {
                    $('#submit').click();
                    setTimeout(init_captcha, 500);
                },
                error: function(res, data) {
                    alert(res.responseJSON.msg);
                    return false;
                }
            });
        });

        init_captcha();
    });
</script>

Django_cbv/themes/bootstrap/templates/comment/result.html
<!doctype html>
<html>
    <head>
        <title>评论结果页 - typeidea</title>
        <style>
        body {TEXT-ALIGN: center;}
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {color: red;}
        ul li {
            list-style-type: None;
        }
        </style>
    </head>
    <body>
        <div class="result">
            {% if succeed %}
                评论成功！
                <a href="{{ target }}">返回</a>
            {% else %}
                <ul class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
                <a href="javascript:window.history.back();">返回</a>
            {% endif %}
        </div>
    </body>
</html>